spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.11:8848
    alicloud:
      sms:
        appcode: 213409bfb6f64fcd9478fda69f2251b1
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: 63698e3463bd490dbc3edc46a20c55f5
    chinatelecom:
      sms:
        host: http://172.16.20.30:31273
        path: /tymh_interface_sms/random_code

server:
  port: 30000

logging:
  level:
    com.gxd.gulimall.thirdparty: debug


